# Generated by Django 4.0 on 2021-12-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='not mentioned', max_length=30)),
                ('email', models.EmailField(default='not mentioned', max_length=254)),
                ('phone', models.CharField(default='not mentioned', max_length=15)),
                ('desc', models.TextField(default='not mentioned')),
            ],
        ),
    ]
