# Generated by Django 4.0 on 2021-12-28 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AIWeb', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 28, 17, 59, 31, 784367, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
