# Generated by Django 4.0 on 2021-12-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIWeb', '0003_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(default='Title ', max_length=25),
        ),
    ]
