# Generated by Django 4.0 on 2021-12-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIWeb', '0004_project_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.JSONField(default={})),
            ],
        ),
    ]
