# Generated by Django 4.0 on 2021-12-28 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AIWeb', '0005_digitalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalnote',
            name='subjectName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalnote',
            name='books',
            field=models.JSONField(default=dict),
        ),
    ]
